using UnityEngine;

public class CheckGround : MonoBehaviour
{
    public static bool isGrounded; // Variable est치tica para verificar si est치 en el suelo

    private void OnTriggerEnter2D(Collider2D collision)
    {
        if (collision.CompareTag("Suelo"))
        {
            isGrounded = true;
            Debug.Log("Ingrid est치 en el suelo"); // Confirmar que se detecta el suelo
        }
    }

    private void OnTriggerExit2D(Collider2D collision)
    {
        if (collision.CompareTag("Suelo"))
        {
            isGrounded = false;
            Debug.Log("Ingrid sali칩 del suelo"); // Confirmar que deja de detectar el suelo
        }
    }
}
